# Generated by Django 2.2.6 on 2019-11-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='equip_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photographer',
            name='profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photographer',
            name='sns',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='')),
                ('zzigsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photographer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
