# Generated by Django 2.2.6 on 2019-11-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_auto_20191125_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zzigsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photographer.Photographer'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='equip_picture',
            field=models.ImageField(blank=True, upload_to='equip'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
