# Generated by Django 2.1.7 on 2019-11-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zzigsa',
            field=models.CharField(choices=[('not yet', 'Not yet'), ('approved', 'Approved'), ('denied', 'Denied')], default='denied', max_length=10),
        ),
    ]
